-- MySQL Script generated by MySQL Workbench
-- Sun Mar  8 11:49:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------



-- -----------------------------------------------------
-- Table `mydb`.`People`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`People` (
  `idPeople` INT NOT NULL,
  `green_coins` VARCHAR(45) NOT NULL,
  `orange_coins` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `birth_date` VARCHAR(45) NOT NULL,
  `work` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPeople`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Adcense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Adcense` (
  `idAdcense` INT NOT NULL,
  `teach` VARCHAR(45) NOT NULL,
  `learn` VARCHAR(45) NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idAdcense`))
ENGINE = InnoDB
COMMENT = 'n';


-- -----------------------------------------------------
-- Table `mydb`.`Match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Match` (
  `idMetch` INT NOT NULL,
  `date_init` VARCHAR(45) NOT NULL,
  `Adcense_idAdcense` INT NOT NULL,
  PRIMARY KEY (`idMetch`, `Adcense_idAdcense`),
  CONSTRAINT `fk_Match_Adcense1`
    FOREIGN KEY (`Adcense_idAdcense`)
    REFERENCES `mydb`.`Adcense` (`idAdcense`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chat` (
  `idChat` INT NOT NULL,
  `Metch_Anuncio_idAnuncio` INT NOT NULL,
  `Match_idMetch` INT NOT NULL,
  `Match_Adcense_idAdcense` INT NOT NULL,
  PRIMARY KEY (`idChat`, `Metch_Anuncio_idAnuncio`, `Match_idMetch`, `Match_Adcense_idAdcense`),
  CONSTRAINT `fk_Chat_Match1`
    FOREIGN KEY (`Match_idMetch` , `Match_Adcense_idAdcense`)
    REFERENCES `mydb`.`Match` (`idMetch` , `Adcense_idAdcense`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`People_has_Adcense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`People_has_Adcense` (
  `People_idPeople` INT NOT NULL,
  `Adcense_idAdcense` INT NOT NULL,
  PRIMARY KEY (`People_idPeople`, `Adcense_idAdcense`),
  CONSTRAINT `fk_People_has_Adcense_People`
    FOREIGN KEY (`People_idPeople`)
    REFERENCES `mydb`.`People` (`idPeople`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_People_has_Adcense_Adcense1`
    FOREIGN KEY (`Adcense_idAdcense`)
    REFERENCES `mydb`.`Adcense` (`idAdcense`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
